// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0sHTDQZJhzY1rwzRqWU4Qe2XJ1idsbpg',
    appId: '1:916306337305:web:ec5e6ea42346c0a153d488',
    messagingSenderId: '916306337305',
    projectId: 'onboard-coolva',
    authDomain: 'onboard-coolva.firebaseapp.com',
    storageBucket: 'onboard-coolva.firebasestorage.app',
    measurementId: 'G-6HSKL9TCC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3AEtbWnicckDAEQLexl5a4PIxyWRqt_4',
    appId: '1:916306337305:android:7428f263d62c64d353d488',
    messagingSenderId: '916306337305',
    projectId: 'onboard-coolva',
    storageBucket: 'onboard-coolva.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_DJQ_hPlhs1P5sQLXP5ML9U1uWJAjjEY',
    appId: '1:916306337305:ios:b5e6c6f078ae036053d488',
    messagingSenderId: '916306337305',
    projectId: 'onboard-coolva',
    storageBucket: 'onboard-coolva.firebasestorage.app',
    iosBundleId: 'com.coolva.robbyonboard.onboardCoolva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_DJQ_hPlhs1P5sQLXP5ML9U1uWJAjjEY',
    appId: '1:916306337305:ios:b5e6c6f078ae036053d488',
    messagingSenderId: '916306337305',
    projectId: 'onboard-coolva',
    storageBucket: 'onboard-coolva.firebasestorage.app',
    iosBundleId: 'com.coolva.robbyonboard.onboardCoolva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0sHTDQZJhzY1rwzRqWU4Qe2XJ1idsbpg',
    appId: '1:916306337305:web:31432dffec317fac53d488',
    messagingSenderId: '916306337305',
    projectId: 'onboard-coolva',
    authDomain: 'onboard-coolva.firebaseapp.com',
    storageBucket: 'onboard-coolva.firebasestorage.app',
    measurementId: 'G-65Z2030329',
  );
}
